server:
  address: ${PORT:8090}

spring:
  application:
    name: project-batch-one
  datasource:
    project:
      url: ${PROJECT_BATCH_JDBC_URL_DB_BATCH}
      username: ${PROJECT_BATCH_JDBC_USER_DB_BATCH}
      password: ${PROJECT_BATCH_JDBC_PASS_DB_BATCH}
    batch:
      url: ${PROCESS_BATCH_JDBC_URL_DB_BATCH}
      username: ${PROCESS_BATCH_JDBC_USER_DB_BATCH}
      password: ${PROCESS_BATCH_JDBC_PASS_DB_BATCH}
  batch:
    jdbc:
      initialize-schema: always
logging:
  config: src/main/resources/log4j.xml