server:
  address: ${PORT:8090}

spring:
  application:
    name: project-batch-one
  datasource:
    batch:
      url: jdbc:mariadb://localhost:3310/batch
      password: secret
      username: study
    h2:
      url: jdbc:h2:mem
      password: sa
      username: sa
  batch:
    jdbc:
      initialize-schema: always