server:
  address: ${PORT:8090}

spring:
  application:
    name: project-batch-one
  datasource:
    url: jdbc:mariadb://localhost:3310/batch
    password: secret
    username: study
  batch:
    jdbc:
      initialize-schema: always